spring.application.name=01-Spring-Practicals

spring.datasource.url= jdbc:postgresql://localhost:5432/student
spring.datasource.username=abcd
spring.datasource.password=abcd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect